### ISSUE TITLE
Lack of pre -

### ISSUE THREAD

**Issue by qsxzaqq** [JHXSMatthew/UHC#1]
GameEvent

**Comment by JHXSMatthew** [comment]
This project is currently not under devs. 
Feel free to creat PR if you wish. 
If you have any request.  Please state it clearly and I will see what I can do. 
Thank you.

**Comment by qsxzaqq** [comment]
Because I want to try and start the plug-in.

**Comment by JHXSMatthew** [comment]
可以使用中文交流。

**Comment by qsxzaqq** [comment]
好的

**Comment by qsxzaqq** [comment]
我太怀念YC了..

本来像原创 然后做到后来

崩溃

**Comment by qsxzaqq** [comment]
然后闲着慌  就搜了一下YourCraft,结果找到了。

**Comment by JHXSMatthew** [comment]
GameEvent 是另一个插件，用来统一做游戏状态控制的。
一会儿传好了贴链接。

**Comment by qsxzaqq** [comment]
好的感谢

**Comment by qsxzaqq** [comment]
问一下dalao是樱花？

**Comment by JHXSMatthew** [comment]
GameEvent 
https://github.com/JHXSMatthew/GameEvent#gameevent

JHXS
